# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bb2dcf2696a4f5411b6f31fd02ae34b5"
name = "scaffold"
handle = "scaffold-8"
application_url = "https://d92c-152-59-102-206.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-12ee8bfe.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://d92c-152-59-102-206.ngrok-free.app/auth/callback",
  "https://d92c-152-59-102-206.ngrok-free.app/auth/shopify/callback",
  "https://d92c-152-59-102-206.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
